"""Write a Markdown snapshot of the course structure that exists today.

Run from backend/main_api:
    python -m course_content.export_structure [--out PATH]

Reads the same source files as the importer (frontend/src/data/*.ts), so the snapshot matches
what the import loads. Use it as a source document for authoring tools and as a diff base.
"""
import argparse
import json
import re
from collections import Counter
from pathlib import Path
from typing import Any, Dict, List

from .import_curriculum import DEFAULT_SOURCE, clean_content, load_source

DATA_DIR = DEFAULT_SOURCE.parent
QUIZ_DIR = DEFAULT_SOURCE.parents[3] / "content" / "Quizzes"
DEFAULT_OUT = Path(__file__).resolve().parents[3] / "docs" / "content-authoring" / "CURRENT_STRUCTURE.md"


def _array(path: Path, name: str) -> List[Dict[str, Any]]:
    text = path.read_text(encoding="utf-8")
    start = text.index("= [", text.index(f"export const {name}")) + 2
    end = text.index("\n];", start) + 2
    return json.loads(text[start:end])


def _object(path: Path, name: str) -> Dict[str, Any]:
    text = path.read_text(encoding="utf-8")
    start = text.index("= {", text.index(f"export const {name}")) + 2
    end = text.index("\n};", start) + 2
    return json.loads(text[start:end])


def _words(text: str) -> int:
    return len(re.findall(r"\w+", text))


def build_markdown() -> str:
    data = load_source(DEFAULT_SOURCE)
    tracks, modules = data["tracks"], data["modules"]
    by_id = {m["id"]: m for m in modules}
    # The quiz bank is server-side now (content/Quizzes/*.json, seeded into the database);
    # it is no longer bundled into the frontend.
    quizzes, diagnostics = {}, []
    for quiz_file in sorted(QUIZ_DIR.rglob("*_questions.json")):
        quiz = json.loads(quiz_file.read_text(encoding="utf-8"))
        if quiz.get("kind") == "diagnostic":
            diagnostics.append(quiz)
        else:
            quizzes[quiz["module_id"]] = quiz
    missions = _array(DATA_DIR / "missionsData.ts", "missionsData")
    rooms = _array(DATA_DIR / "escapeRoomData.ts", "escapeRoomScenarios")
    badges = _array(DATA_DIR / "badgesData.ts", "badgesData")
    certs = _array(DATA_DIR / "badgesData.ts", "certificatesData")
    # The diagnostic is a server-side quiz module (content/Quizzes/Diagnostic) since T1.5.
    assessment_domains = Counter(q.get("domain") for d in diagnostics for q in d["questions"])

    total_sections = sum(len(m["sections"]) for m in modules)
    thin = sum(1 for m in modules for s in m["sections"] if _words(clean_content(s["content"])) < 40)
    out: List[str] = []
    w = out.append

    w("# Q-CAPS current course structure\n")
    w("Generated by `python -m course_content.export_structure` from `frontend/src/data`. "
      "Do not edit by hand; regenerate after content changes.\n")
    w("## Totals\n")
    w(f"- Tracks: {len(tracks)}")
    w(f"- Modules: {len(modules)}")
    w(f"- Sections (lessons): {total_sections}, of which {thin} have fewer than 40 words")
    w(f"- Module quizzes: {len(quizzes)} ({sum(len(q['questions']) for q in quizzes.values())} questions)")
    w(f"- Missions: {len(missions)}; escape-room scenarios: {len(rooms)}")
    w(f"- Diagnostic assessment questions: {sum(assessment_domains.values())}; badges: {len(badges)}; certificates: {len(certs)}\n")

    w("## How the pieces are named\n")
    w("| Term in this document | Meaning |")
    w("|---|---|")
    w("| Track | A course: a sequence of modules ending in a capstone and certificate |")
    w("| Module | A unit of study with objectives, prerequisites, XP and a quiz |")
    w("| Section | A lesson inside a module; stored as an ordered list of content blocks |")
    w("| Slug | The stable ID used in URLs and prerequisites, e.g. `track_b_b9_pqc_fundamentals` |")
    w("| Section slug | `sec-N` for existing sections; new sections use lowercase words with hyphens |\n")

    w("## Tracks and modules\n")
    for t in tracks:
        w(f"### {t['code']}: {t['title']} (`{t['id']}`)\n")
        w(f"*{t['subtitle']}*\n")
        w(f"- Entry profile: {t['entryProfile']}")
        w(f"- Certificate: {t['certificateName']} ({t['certificateCode']})")
        w(f"- Capstone: {t['capstoneTitle']}: {t['capstoneDescription']}\n")
        for mid in t["moduleIds"]:
            m = by_id[mid]
            prereq = ", ".join(by_id[p]["code"] for p in m["prerequisites"] if p in by_id) or "none"
            quiz = quizzes.get(mid)
            linked = [x["title"] for x in missions if x.get("linked_module_id") == mid]
            w(f"#### {m['code']} {m['title']}\n")
            w(f"- Slug: `{m['id']}`")
            w(f"- Level: {m['level']}; about {m['estimatedMinutes']} min; {m['xp']} XP; domain: {m.get('domain', 'n/a')}; "
              f"recommendation topic: {m.get('recommendationTopic', 'n/a')}")
            w(f"- Prerequisites: {prereq}")
            w(f"- Quiz: {len(quiz['questions']) if quiz else 0} questions"
              + (f"; linked mission: {', '.join(linked)}" if linked else ""))
            if m["learningObjectives"]:
                w("- Learning objectives:")
                for o in m["learningObjectives"]:
                    w(f"  - {o}")
            w("- Sections:")
            for s in m["sections"]:
                body = clean_content(s["content"])
                note = "stub" if _words(body) < 40 else f"{_words(body)} words"
                w(f"  - `{s['id']}` {s['title']} ({note})")
            w("")

    w("## Missions\n")
    for x in missions:
        w(f"- `{x['mission_id']}`: {x['title']} ({x['type']}); linked module `{x['linked_module_id']}`")
    w("\n## Escape-room scenarios\n")
    for r in rooms:
        linked = r.get("module_id", "")
        status = "ok" if linked in by_id else "NO MATCHING MODULE (legacy ID)"
        w(f"- `{r.get('id', '')}` {r.get('title', '')}; module_id `{linked}`: {status}")
    w("\n## Diagnostic assessment (domains)\n")
    for domain, n in assessment_domains.items():
        w(f"- {domain}: {n} questions")
    w("\n## Badge and certificate counts\n")
    w(f"- Badges by category: {dict(Counter(b['category'] for b in badges))}")
    w(f"- Certificates: {', '.join(c['title'] for c in certs)}")
    w("\n## Known gaps\n")
    broken = [r.get("id") for r in rooms if r.get("module_id", "") not in by_id]
    if broken:
        w(f"- Escape-room scenarios with a legacy module_id that matches no module: {len(broken)} of {len(rooms)}.")
    w("- No bibliography or source field on any section, module or quiz question yet.")
    w("- No Research Papers or References content type yet.")
    w("- PQC and Quantum Cybersecurity are tags (`domain`), not top-level categories.")
    w("- Competency tags on quiz items, labs and missions are drafts (proposed-unreviewed) until an expert reviews them.")
    return "\n".join(out) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(build_markdown(), encoding="utf-8", newline="\n")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
