// src/services/backendService.ts
// Integration layer communicating with Vishnu Priya's Analytics Backend (Python FastAPI)
// Location: Q-CAPS-vishnu-priya-backend/backend/main.py (Port 8000)

const BACKEND_BASE_URL =
  import.meta.env.VITE_API_BASE_URL || 'http://localhost:8000/api';

export interface UserProfile {
  user_id: string;
  name: string;
  email: string;
  readiness_score: number;
  total_xp: number;
  global_rank: number;
  unlocked_badges: string[];
  recommended_next_module: string;
}

export interface UserRecommendation {
  course_id: string | null;
  title: string | null;
  topic: string | null;
  priority: string;
  reason: string;
  quiz_score: number | null;
  scanner_risk: string | null;
  status: string;
}

export interface LeaderboardEntry {
  id: number;
  name: string;
  xp: number;
  rank: number;
}

export interface QuizSubmissionPayload {
  user_id: number;
  topic: string;
  correct_answers: number;
  total_questions: number;
}

export interface ScannerLogPayload {
  user_id: number;
  endpoint: string;
  status: string;
  vulnerabilities_found: number;
  details?: string;
}

/**
 * Check if the Analytics Backend is online
 */
export async function checkBackendHealth(): Promise<boolean> {
  try {
    const res = await fetch(`${BACKEND_BASE_URL}/health`, {
      method: 'GET',
      headers: { 'Content-Type': 'application/json' },
    });
    if (!res.ok) return false;
    const data = await res.json();
    return data.status === 'healthy';
  } catch {
    return false;
  }
}

/**
 * Fetch common user profile (matching shared_data_schema.md)
 */
export async function fetchUserProfile(userId: number = 1): Promise<UserProfile | null> {
  try {
    const res = await fetch(`${BACKEND_BASE_URL}/users/${userId}/profile`);
    if (!res.ok) {
      if (res.status === 404) {
        // Try creating the default user if not found
        await createUser('Operator');
        const retryRes = await fetch(`${BACKEND_BASE_URL}/users/${userId}/profile`);
        if (retryRes.ok) return await retryRes.json();
      }
      return null;
    }
    return await res.json();
  } catch (error) {
    console.debug('Backend offline or unavailable, falling back to local data.', error);
    return null;
  }
}

/**
 * Fetch personalized recommendation generated by the recommendation algorithm
 */
export async function fetchUserRecommendation(userId: number = 1): Promise<UserRecommendation | null> {
  try {
    const res = await fetch(`${BACKEND_BASE_URL}/users/${userId}/recommendation`);
    if (!res.ok) return null;
    return await res.json();
  } catch (error) {
    console.debug('Failed to fetch recommendation from backend:', error);
    return null;
  }
}

/**
 * Fetch global leaderboard data
 */
export async function fetchLeaderboard(): Promise<LeaderboardEntry[]> {
  try {
    const res = await fetch(`${BACKEND_BASE_URL}/leaderboard`);
    if (!res.ok) return [];
    return await res.json();
  } catch (error) {
    console.debug('Failed to fetch leaderboard:', error);
    return [];
  }
}

/**
 * Submit quiz score to calculate XP and update user skill gap model
 */
export async function submitQuizScore(payload: QuizSubmissionPayload) {
  try {
    const res = await fetch(`${BACKEND_BASE_URL}/quizzes/submit`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    });
    if (!res.ok) throw new Error(`HTTP error ${res.status}`);
    return await res.json();
  } catch (error) {
    console.warn('Failed to submit quiz score to backend:', error);
    return null;
  }
}

/**
 * Record a scan log into the backend database to feed the recommendation engine
 */
export async function logScannerResult(payload: ScannerLogPayload) {
  try {
    const res = await fetch(`${BACKEND_BASE_URL}/scanner/log`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload),
    });
    if (!res.ok) throw new Error(`HTTP error ${res.status}`);
    return await res.json();
  } catch (error) {
    console.warn('Failed to log scanner finding to backend:', error);
    return null;
  }
}

/**
 * Create a new user in the backend
 */
export async function createUser(name: string) {
  try {
    const res = await fetch(`${BACKEND_BASE_URL}/users`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ name }),
    });
    if (!res.ok) throw new Error(`HTTP error ${res.status}`);
    return await res.json();
  } catch (error) {
    console.warn('Failed to create user on backend:', error);
    return null;
  }
}
