// Generated from Content-Security/Mission
export interface MissionData {
  mission_id: string;
  title: string;
  type: 'simulation' | 'decision_scenario';
  linked_module_id: string;
  role: string;
  objective: string;
  environment: string;
  state_variables: Record<string, unknown>;
  stages: Record<string, unknown>[];
  resolution?: Record<string, unknown>;
  replayability_note?: string;
  rewards?: Record<string, unknown>;
  [key: string]: unknown;
}

export const missionsData: MissionData[] = [
  {
    "mission_id": "mission_bb84_diplomatic_channel",
    "title": "Secure the Diplomatic Channel",
    "type": "simulation",
    "linked_module_id": "track_c_c6_quantum_key_distribution",
    "role": "You are the on-site quantum communications officer for a diplomatic mission.",
    "objective": "Establish a shared secret key between Alice (your embassy) and Bob (the receiving embassy) that you can trust has not been intercepted.",
    "environment": "You have: a quantum channel (single-photon transmission), a classical channel (for comparing bases only — never the actual bit values), a photon source at Alice's end, polarization measurement equipment at Bob's end, and limited bandwidth (you can only send a few hundred photons before the diplomatic window closes).",
    "state_variables": {
      "alice_bits": "array of random 0/1 values generated per photon sent",
      "alice_bases": "array of randomly chosen '+' (rectilinear) or 'x' (diagonal) bases, one per photon",
      "bob_bases": "array of randomly chosen '+' or 'x' bases, independently chosen by Bob before measuring",
      "bob_results": "array of Bob's measured bit values — computed by the simulation engine per the rules in Stage 2",
      "matching_basis_mask": "boolean array — true where alice_bases[i] == bob_bases[i]",
      "sifted_key": "the subset of alice_bits (or bob_results) where matching_basis_mask is true",
      "eve_present": "boolean, hidden from the learner until Stage 4 — controls whether interception noise is injected",
      "sample_comparison_size": "number of sifted key bits the learner chooses to publicly compare to estimate error rate",
      "observed_error_rate": "computed percentage mismatch in the compared sample",
      "key_accepted": "boolean, learner's final decision"
    },
    "stages": [
      {
        "stage_id": "stage_1_setup",
        "narrative": "The mission briefing loads. You're told the basics of your equipment but NOT told how basis choice affects measurement — that's what you're about to discover.",
        "learner_action": "Choose a batch size (e.g., 50 photons) and click 'Begin Transmission.' Alice's bits and bases are randomly generated by the simulation; the learner does not choose Alice's values directly, only initiates the process — this mirrors real BB84 where the sender's choices are random, not learner-scripted.",
        "system_reaction": "For each photon, Bob independently and randomly chooses his own measurement basis ('+' or 'x') BEFORE seeing Alice's choice — the simulation should visually emphasize that Bob's basis choice happens with zero knowledge of Alice's.",
        "🎨 interactive_visual": "Photon-by-photon animation: each photon shown traveling from Alice to Bob with its (hidden from Bob) polarization, Bob's basis choice shown as a dial he sets independently, then a measurement result pops out."
      },
      {
        "stage_id": "stage_2_measure_and_notice",
        "narrative": "Transmission complete. Bob has a full set of measurement results. Something looks off.",
        "learner_action": "The learner views a table: Alice's basis, Bob's basis, Bob's result. They're prompted: 'Look at the rows where the bases DON'T match. What do you notice about Bob's results there?'",
        "system_reaction": "Simulation engine rule (not shown to learner yet, only its OUTPUT is shown): when bases match, Bob's result equals Alice's bit with certainty. When bases DON'T match, Bob's result is uniformly random (50/50), regardless of Alice's actual bit — this is the real quantum-mechanical behavior of measuring in an incompatible basis, computed honestly by the simulation, not faked.",
        "investigation_prompt": "The learner is asked to form a hypothesis before being told the answer: 'Why do you think mismatched-basis rows look random?' — free-text or multiple-choice reflection, not graded, just prompts genuine engagement before the reveal.",
        "concept_reveal_partial": "AFTER the learner submits a hypothesis (right or wrong): 'When Bob measures in a basis different from how Alice encoded the photon, quantum mechanics gives a random result — this isn't equipment error, it's fundamental. This is exactly why BB84 only keeps bits where the bases happened to match.'",
        "🎨 interactive_visual": "Highlight matching-basis rows in green, mismatched in red, with the random-looking red results visually 'shuffling' to emphasize their randomness."
      },
      {
        "stage_id": "stage_3_sift_the_key",
        "narrative": "Now that you understand why mismatched bases produce garbage, it's time to build the actual shared key.",
        "learner_action": "The learner publicly compares (over the classical channel) ONLY the basis choices (never the bit values) for each photon, discards every row where bases didn't match, and is left with the sifted key — roughly half the original transmission, as expected.",
        "system_reaction": "Sifted key is computed and displayed. Mission tracks `sifted_key` state variable.",
        "🎨 interactive_visual": "Animated 'sifting' where mismatched rows visibly fall away, leaving only the matched rows forming the key."
      },
      {
        "stage_id": "stage_4_security_alert",
        "narrative": "⚠️ SECURITY ALERT: Your quantum channel has been compromised. (Internally: `eve_present` is now set to true for this run — the learner doesn't know this yet, only that something triggered the alert.)",
        "learner_action": "The learner is told error-checking is now mandatory before trusting this key. They choose a sample of bits from the sifted key to publicly compare (sacrificing those bits — they can't be used in the final key either way).",
        "system_reaction": "The simulation computes `observed_error_rate` honestly: with `eve_present = true`, an eavesdropper measuring photons in transit (necessarily guessing bases herself, same as Bob) introduces detectable disturbance — roughly 25% error rate in the compared sample, versus near-0% in a clean run. The exact rate should have realistic random variance, not a fixed constant, so repeated missions don't all show identically '25.00%.'",
        "investigation_prompt": "Learner is shown the observed error rate and asked: 'Based on this number, do you think this key is safe to use?' — before any threshold is given to them.",
        "🎨 interactive_visual": "A live-updating error-rate gauge as the learner selects more sample bits to compare — larger samples give a more statistically confident (and stable) reading, teaching sample-size intuition as a side effect."
      },
      {
        "stage_id": "stage_5_decide",
        "narrative": "You must decide: ACCEPT the key and use it, or ABORT and request retransmission.",
        "learner_action": "Binary decision: Accept or Abort.",
        "consequences": {
          "accept_with_low_error": "Correct call if error rate is near the expected quantum-channel-noise baseline (a few percent, representing normal equipment imperfection, not attack) — mission succeeds.",
          "accept_with_high_error": "Wrong call — mission fails with a debrief: 'You used a compromised key. In a real deployment, this would have handed Eve your diplomatic communications.'",
          "abort_with_low_error": "Overly cautious but not wrong — mission succeeds with a note: 'You were safe, but excessive caution costs operational time. In practice, thresholds are set statistically, not by gut feeling.'",
          "abort_with_high_error": "Correct call — mission succeeds. This is the intended 'win' path when `eve_present` is true."
        }
      }
    ],
    "resolution": {
      "success_condition": "Learner correctly aborts when error rate exceeds the normal noise baseline, or correctly accepts when it's within baseline.",
      "failure_condition": "Learner accepts a key with an error rate indicating interception.",
      "concept_reveal": "Full explanation shown at mission end regardless of outcome: 'BB84's security comes from a physical fact, not a policy: an eavesdropper (Eve) intercepting photons must also guess a measurement basis, exactly like Bob does. When her guess is wrong (which happens roughly half the time), she disturbs the photon's state — and that disturbance shows up as extra errors when Alice and Bob compare a sample of their sifted key. No amount of computing power lets Eve avoid this — it's a consequence of quantum measurement itself, not classical cryptography's computational hardness assumptions.' This explicitly ties back to the QKD-vs-PQC distinction taught in Track B/C: this security guarantee is physics-based, which is exactly why QKD doesn't need the 'is the math still hard against future computers' hedge that PQC does — but also why it needs specialized hardware PQC doesn't."
    },
    "rewards": {
      "badge_awarded": "QKD Defender",
      "mission_xp_awarded": 85
    },
    "replayability_note": "Each mission run should randomize eve_present and the specific error-rate variance, so replaying the mission doesn't always show the identical numbers — reinforces that the learner is reasoning about statistics, not memorizing a fixed scenario outcome."
  },
  {
    "mission_id": "mission_pqc_migration_enterprise",
    "title": "The Migration Mandate",
    "type": "decision_scenario",
    "linked_module_id": "track_d_e5_enterprise_pqc_migration",
    "role": "You are the newly appointed Security Architect for a mid-size financial services company.",
    "objective": "Lead your organization through a quantum-safe migration before your board-mandated 18-month deadline, without causing a business-continuity incident.",
    "environment": "Your organization has: 10,000 employee/customer-facing devices, a legacy PKI with RSA-2048 certificates, a customer-facing TLS API layer, an internal VPN, and a 20-year regulatory data-retention requirement on customer financial records.",
    "state_variables": {
      "readiness_score": "0-100, starts at 12 (mostly unassessed)",
      "business_continuity_score": "0-100, starts at 100, decreases with risky/rushed decisions",
      "budget_remaining": "starts at 100 (percent), decreases per stage based on choices made",
      "time_remaining_months": "starts at 18, decreases per stage",
      "discovered_assets": "0 until Stage 1 is resolved",
      "chosen_algorithms": "map of asset-category to selected PQC algorithm, populated across Stage 3",
      "hybrid_mode_enabled": "boolean, set in Stage 3"
    },
    "stages": [
      {
        "stage_id": "stage_1_the_alert",
        "narrative": "🚨 Quantum Vulnerability Detected. Your compliance team flags that your organization's cryptographic posture has never been formally assessed against post-quantum risk. The board wants a plan in 2 weeks.",
        "decision_prompt": "What's your first move?",
        "choices": [
          {
            "id": "a",
            "text": "Immediately start migrating the customer-facing TLS API, since it's the most visible system.",
            "consequence": {
              "readiness_score": -5,
              "business_continuity_score": -10
            },
            "feedback": "Risky — migrating before discovery means you don't actually know your full exposure. You might miss higher-risk systems (like the 20-year-retention data) while working on a lower-priority one."
          },
          {
            "id": "b",
            "text": "Commission a full cryptographic discovery and inventory before touching anything.",
            "consequence": {
              "readiness_score": 15,
              "time_remaining_months": -1
            },
            "feedback": "Correct instinct — this is the 'Discover → Inventory' foundation the whole migration process depends on. Costs a month, but every later decision will be evidence-based instead of guesswork."
          },
          {
            "id": "c",
            "text": "Tell the board quantum computers don't exist yet, so there's no real urgency.",
            "consequence": {
              "readiness_score": -15,
              "business_continuity_score": -5
            },
            "feedback": "This ignores Harvest-Now-Decrypt-Later risk — your 20-year data retention requirement means data captured today is already exposed to future decryption. This answer would not survive a real board Q&A."
          }
        ]
      },
      {
        "stage_id": "stage_2_the_inventory_reveals",
        "narrative": "Discovery is complete. Your cryptographic inventory shows: 6,000 devices using RSA-2048 for TLS, 3,500 using ECDSA-256 for VPN authentication, and 500 legacy devices you can't easily update (embedded firmware, vendor-locked).",
        "decision_prompt": "How do you prioritize?",
        "choices": [
          {
            "id": "a",
            "text": "Migrate everything simultaneously to hit the deadline faster.",
            "consequence": {
              "business_continuity_score": -25,
              "budget_remaining": -30
            },
            "feedback": "A 'big bang' migration across 10,000 devices with no piloting is exactly the scenario that causes real production outages — several documented real-world migration failures follow this pattern."
          },
          {
            "id": "b",
            "text": "Prioritize by risk: the systems protecting the 20-year-retention financial data first, piloted on a small subset before wider rollout.",
            "consequence": {
              "readiness_score": 20,
              "business_continuity_score": 10
            },
            "feedback": "Correct — this follows the Risk-Rank → Prototype → Pilot sequence. The long-lived sensitive data carries the highest HNDL exposure, so it should lead, and piloting protects business continuity."
          },
          {
            "id": "c",
            "text": "Deprioritize everything and focus only on the 500 legacy embedded devices since they're the hardest problem.",
            "consequence": {
              "readiness_score": -5,
              "time_remaining_months": -2
            },
            "feedback": "Tackling the hardest, lowest-volume problem first while leaving 9,500 higher-exposure devices unaddressed is a poor use of your limited timeline — sequencing should follow risk and feasibility together, not just difficulty."
          }
        ]
      },
      {
        "stage_id": "stage_3_algorithm_selection",
        "narrative": "You've prioritized the TLS-facing RSA-2048 fleet and the VPN's ECDSA-256 authentication. Now you need to select PQC algorithms and decide on hybrid vs. pure deployment.",
        "decision_prompt": "For the TLS key exchange (currently RSA), what do you select?",
        "choices": [
          {
            "id": "a",
            "text": "ML-KEM, deployed in hybrid mode alongside the existing classical exchange.",
            "consequence": {
              "readiness_score": 15,
              "business_continuity_score": 5,
              "chosen_algorithms": {
                "tls_key_exchange": "ML-KEM (hybrid)"
              },
              "hybrid_mode_enabled": true
            },
            "feedback": "This is the current best-practice choice — hybrid deployment hedges against both a future quantum break of the classical component AND any early implementation flaw in the newer PQC component."
          },
          {
            "id": "b",
            "text": "ML-KEM, pure PQC only, dropping the classical fallback immediately for maximum quantum-safety.",
            "consequence": {
              "readiness_score": 5,
              "business_continuity_score": -15
            },
            "feedback": "Technically quantum-safe, but abandons crypto-agility's risk-hedging benefit during the period when ML-KEM implementations are still relatively new and less battle-tested than decades-old classical algorithms."
          },
          {
            "id": "c",
            "text": "SLH-DSA for the key exchange, since it's the most conservative option.",
            "consequence": {
              "readiness_score": -10,
              "budget_remaining": -20
            },
            "feedback": "Algorithm/purpose mismatch — SLH-DSA is a signature scheme, not a key exchange mechanism. This choice wouldn't even function correctly in a TLS handshake."
          }
        ]
      },
      {
        "stage_id": "stage_4_the_benchmark_surprise",
        "narrative": "Your pilot deployment (hybrid ML-KEM on 200 devices) is running. Performance monitoring shows a measurable latency increase on your oldest device tier — larger key sizes mean more handshake overhead.",
        "decision_prompt": "How do you respond?",
        "choices": [
          {
            "id": "a",
            "text": "Halt the entire migration until the performance issue is fully resolved for every device tier.",
            "consequence": {
              "time_remaining_months": -3,
              "business_continuity_score": 5
            },
            "feedback": "Safe but slow — you have 18 months total and this consumes a lot of it. Reasonable if the impact is severe, but worth checking whether it actually affects user experience meaningfully first."
          },
          {
            "id": "b",
            "text": "Check whether the latency increase is actually noticeable to end users before deciding whether it's a real problem.",
            "consequence": {
              "readiness_score": 10,
              "business_continuity_score": 10
            },
            "feedback": "The disciplined move — the Benchmark phase exists precisely to catch this kind of issue during piloting, on a small scale, before full rollout. Measuring actual user impact (not just raw latency numbers) is how real migration teams make this call."
          },
          {
            "id": "c",
            "text": "Ignore it and proceed straight to full production rollout across all 10,000 devices.",
            "consequence": {
              "business_continuity_score": -20,
              "readiness_score": -5
            },
            "feedback": "Skipping the lesson the pilot was designed to teach — rolling out an unresolved performance issue to your full fleet risks a much larger-scale problem than the one you already detected at small scale."
          }
        ]
      },
      {
        "stage_id": "stage_5_final_report",
        "narrative": "18 months (adjusted by your time-management decisions) later, your board wants a final readiness report.",
        "decision_prompt": "Based on your accumulated readiness_score and business_continuity_score, the mission resolves automatically — no further choice here, but the outcome depends entirely on your path through Stages 1-4.",
        "outcome_bands": {
          "readiness_score_75_plus_and_continuity_60_plus": "SUCCESS — Full Migration Complete. Your board approves the final report; the organization is genuinely quantum-ready and didn't sacrifice operational stability to get there.",
          "readiness_score_50_to_74": "PARTIAL SUCCESS — Migration In Progress, On Track. You've made real, defensible progress but haven't finished — a realistic and common outcome for a first migration cycle.",
          "readiness_score_below_50_or_continuity_below_40": "AT RISK — the board is not satisfied. Debrief explains which specific decisions (traceable to the stage choices made) drove the shortfall, so the learner can see exactly where the path diverged."
        }
      }
    ],
    "resolution": {
      "success_condition": "Combined readiness_score and business_continuity_score both land in healthy ranges by Stage 5 — see outcome_bands above.",
      "failure_condition": "Either score falls critically low due to rushed, under-prepared, or poorly sequenced decisions.",
      "concept_reveal": "Full debrief shown at mission end: 'Real enterprise PQC migration isn't a single technical decision — it's a sequence: Discover, Inventory, Classify, Risk-Rank, Select PQC, Prototype, Benchmark, Pilot, Hybrid Migration, Production Rollout, Monitor, Retire. Skipping steps to move faster (as tempting as it is under a board deadline) is exactly what causes real-world migration failures. The tradeoffs you just navigated — speed vs. safety, aggressive vs. cautious algorithm choices, ignoring vs. investigating pilot data — are the actual judgment calls a Security Architect faces, not hypothetical exam questions.'"
    },
    "rewards": {
      "badge_awarded": "Migration Commander",
      "mission_xp_awarded": 100
    },
    "replayability_note": "Multiple valid paths exist through this mission — a cautious, slower path and a leaner, faster path can both reach SUCCESS if internally consistent (e.g., consistently risk-driven and evidence-based). The mission should NOT have one single 'correct' route; it should reward sound reasoning patterns across different valid strategies, mirroring how real migrations don't have one universally correct playbook either."
  }
];
